# Generated by Django 3.1.7 on 2021-03-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phoneNum', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataId', models.CharField(max_length=20)),
                ('operationType', models.CharField(max_length=20)),
                ('originData', models.CharField(max_length=255)),
                ('resultData', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
                ('clinicId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataId', models.CharField(max_length=20)),
                ('operationType', models.CharField(max_length=20)),
                ('originData', models.CharField(max_length=255)),
                ('resultData', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataId', models.CharField(max_length=20)),
                ('operationType', models.CharField(max_length=20)),
                ('originData', models.CharField(max_length=255)),
                ('resultData', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=5)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataId', models.CharField(max_length=20)),
                ('operationType', models.CharField(max_length=20)),
                ('originData', models.CharField(max_length=255)),
                ('resultData', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('phoneNum', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(max_length=20)),
                ('feature', models.CharField(max_length=20)),
                ('treatment', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
                ('doctorId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
