# Generated by Django 3.1.7 on 2021-03-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliniclog',
            old_name='userId',
            new_name='operatorId',
        ),
        migrations.RenameField(
            model_name='doctorlog',
            old_name='userId',
            new_name='operatorId',
        ),
        migrations.RenameField(
            model_name='prescriptionlog',
            old_name='userId',
            new_name='operatorId',
        ),
        migrations.RenameField(
            model_name='userlog',
            old_name='userId',
            new_name='operatorId',
        ),
    ]
