# Generated by Django 3.1.7 on 2021-03-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210310_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
