# Generated by Django 3.1.7 on 2021-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_clinic_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='department',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
