# Generated by Django 3.1.7 on 2021-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_clinic_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
