# Generated by Django 3.1.7 on 2021-03-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinicId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.clinic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='userId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctorId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.doctor'),
        ),
    ]
